name: Close stale issues and PRs
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.0.0
        with:
          stale-issue-message: 'This issue has had no activity in the last 60 days. Please add a reply if you want to keep this issue active, otherwise it will be automatically closed after 30 days.'
          stale-pr-message: 'This PR has had no activity in the last 60 days. Please add a reply if you want to keep this PR active, otherwise it will be automatically closed after 30 days.'
          close-issue-message: 'This issue was closed because of inactivity. If this issue is still relevant, please re-open a new issue.'
          close-pr-message: 'This PR was closed because of inactivity. If this PR is still relevant, please re-open a new PR.'
          days-before-issue-stale: 60
          days-before-pr-stale: 60
          days-before-issue-close: 30
          days-before-pr-close: 30
          # Don't add stale label to PRs / issues with this label
          exempt-issue-labels: 'never-stale'
          exempt-pr-labels: 'never-stale'

